name: Change target branch to development

on:
  pull_request:
    types: [opened]

jobs:
  check_and_set_target:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Change Target Branch if Bot Author
        if: ${{ steps.pr_info.outputs.PR_AUTHOR == 'ykyivskyi-gl' && steps.pr_info.outputs.CURRENT_BASE_BRANCH != 'development' }}
        run: |
          PR_NUMBER="${{ steps.pr_info.outputs.PR_NUMBER }}"
          NEW_BASE_BRANCH="development"
          CURRENT_BASE_BRANCH="${{ steps.pr_info.outputs.CURRENT_BASE_BRANCH }}"

          gh pr edit "$PR_NUMBER" --base "$NEW_BASE_BRANCH" --repo "${{ github.repository }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required for gh CLI authentication

      - name: Log if no change needed (for clarity)
        if: ${{ steps.pr_info.outputs.PR_AUTHOR != 'ykyivskyi-gl' || steps.pr_info.outputs.CURRENT_BASE_BRANCH == 'development' }}
        run: |
          PR_AUTHOR="${{ steps.pr_info.outputs.PR_AUTHOR }}"
          CURRENT_BASE_BRANCH="${{ steps.pr_info.outputs.CURRENT_BASE_BRANCH }}"
          PR_NUMBER="${{ steps.pr_info.outputs.PR_NUMBER }}"

          if [[ "$PR_AUTHOR" != "ykyivskyi-gl" ]]; then
            echo "PR #$PR_NUMBER was opened by '$PR_AUTHOR'. Not 'ykyivskyi-gl'. No base branch change will occur."
          elif [[ "$CURRENT_BASE_BRANCH" == "development" ]]; then
            echo "PR #$PR_NUMBER by 'ykyivskyi-gl' already targets 'development'. No change needed."
          fi
